(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))c(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(n){if(n.ep)return;n.ep=!0;const s=o(n);fetch(n.href,s)}})();function h(e=""){return fetch(`https://app.ticketmaster.com/discovery/v2/events.json?apikey=rvylvsHWc98giycRfhDFKtIp8G9FNDPl${e}`).then(t=>t.json())}const d=document.querySelector(".hero__list"),p=document.querySelector(".header__inp"),y=document.querySelector(".header__btn"),i=document.querySelector(".header__input");let u=[];function g(e){let t="./img/modal-decstop.jpg";if(e.images&&e.images.length>0){for(let s=0;s<e.images.length;s++)if(e.images[s].width>=640){t=e.images[s].url;break}t==="./img/modal-decstop.jpg"&&(t=e.images[0].url)}const o=e.name,c=e.dates&&e.dates.start&&e.dates.start.localDate?e.dates.start.localDate:"Unknown date";let n="Unknown place";return e._embedded&&e._embedded.venues&&e._embedded.venues.length>0&&e._embedded.venues[0].name&&(n=e._embedded.venues[0].name),`
    <li class="hero__item">
      <div class="hero__card">
        <img class="hero__icon" src="./img/img-event.svg" alt="">
        <img src="${t}" alt="${o}" class="hero__images" />
        <h3 class="hero__title">${o}</h3>
        <div class="hero__box">
          <svg class="hero__img">
            <use href="./img/symbol-defs.svg#icon-place"></use>
          </svg>
          <h4 class="hero__desk">${n}</h4>
        </div>
        <p class="hero__text">${c}</p>
      </div>
    </li>
  `}function _(e){d.innerHTML=e.map(g).join("")}function v(){const e=p.value.trim(),t=i.value;let o="&size=30";return e&&e.length>0&&(o+="&keyword="+encodeURIComponent(e)),t&&t.length>0&&(o+="&countryCode="+t),o}function a(){h(v()).then(function(e){e._embedded&&e._embedded.events&&e._embedded.events.length>0?(u=e._embedded.events,_(u)):d.innerHTML="<li>Nothing found</li>"}).catch(function(e){console.error(e),d.innerHTML="<li>Nothing found</li>"})}y.addEventListener("click",function(e){e.preventDefault(),a()});p.addEventListener("input",a);i.addEventListener("change",a);a();async function b(){return(await(await fetch("https://restcountries.com/v3.1/all?fields=name,cca2")).json()).filter(o=>{var c;return o.cca2&&((c=o.name)==null?void 0:c.common)}).map(o=>({code:o.cca2,name:o.name.common})).sort((o,c)=>o.name.localeCompare(c.name,"uk"))}async function E(e){const t=await b(),o='<option value="">All countries</option>',c=t.map(n=>`<option value="${n.code}">${n.name} (${n.code})</option>`).join("");e.innerHTML=o+c,e.value=""}async function m(e){let t="https://app.ticketmaster.com/discovery/v2/events.json?size=10&apikey=rvylvsHWc98giycRfhDFKtIp8G9FNDPl";return e!==""&&(t+=`&countryCode=${encodeURIComponent(e)}`),(await fetch(t)).json()}document.addEventListener("DOMContentLoaded",async()=>{await E(i);const e=await m("");console.log(e),i.addEventListener("change",async t=>{const o=t.target.value,c=await m(o);console.log(c)})});const f=document.querySelector(".backdrop");document.querySelector(".modal__btn");const L=document.querySelector(".hero");L.addEventListener("click",e=>{if(e.target.closest(".hero__item"))f.style.opacity="1",f.style.pointerEvents="all";else return});const r=document.querySelector(".backdrop"),k=document.querySelector(".modal__btn");k.addEventListener("click",()=>{r.style.opacity="0",r.style.pointerEvents="none"});r.addEventListener("click",()=>{r.style.opacity="0",r.style.pointerEvents="none"});
//# sourceMappingURL=commonHelpers.js.map
